require 'user.leap'
require 'user.leap-spooky'
require 'user.flit'
require 'user.telescope'
require 'user.neoclip'
require 'user.lsp'(capabilities)
-- require 'user.neodev'
require 'user.orgmode'
require 'user.treesitter'
require 'user.treesitter-context'
require 'user.treesitter-textobjects'
require 'user.dap'
require 'user.dap-ui'
require 'user.colorscheme'
require 'user.easypick'
require 'user.pomo'
require 'user.gitsigns'
require 'user.coq'
require 'user.psql'
require 'user.neocomposer'
-- require 'user.oil'
require 'user.persisted'
require 'user.autolist'
-- require 'user.auto-session'
